//TODO: Separate these into their respective files
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const RELOG_REQUEST = 'RELOG_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const SELECT_REGION = 'SELECT_REGION';
export const SEARCH_PLAYER_REQUEST = 'SEARCH_PLAYER_REQ';
export const SEARCH_PLAYER_FOUND_DB = 'SEARCH_PLAYER_FOUND_DB';
export const SEARCH_PLAYER_NOT_FOUND_DB = 'SEARCH_PLAYER_NOT_FOUND_DB';
export const SEARCH_PLAYER_CLEAR = 'SEARCH_PLAYER_CLEAR';
export const SEARCH_PLAYER_DETAIL = 'SEARCH_PLAYER_DETAIL';
export const SEARCH_PLAYER_NO_DETAIL = 'SEARCH_PLAYER_NO_DETAIL';
export const SEARCH_PLAYER_FOUND_DETAIL = 'SEARCH_PLAYER_FOUND_DETAIL';
